services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    expose:
      # Opens port 3306 on the container
      - "${MYSQL_PORT}"
    volumes:
      - /home/anderson/mysql:/var/lib/mysql